// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TMMoveEx","status":true,"description":"壁衝突音やリージョンによる通行設定などの機能を追加します。","parameters":{"passableRegionId":"251","dontPassRegionId":"252","seKnockWall":"<name:Blow1><volume:90><pitch:100>","knockWallPan":"75","knockWallInterval":"30","turnKeyCode":"83","movableRegion1":"","movableRegion2":"","movableRegion3":"","movableRegion4":"","movableRegion5":"","movableRegion6":"","movableRegion7":"","movableRegion8":"","movableRegion9":"","movableRegion10":""}},
{"name":"EyePhoneMenu","status":true,"description":"","parameters":{}},
{"name":"TitleAnimation","status":true,"description":"タイトル画面にアニメーション表示します。","parameters":{"name":"tittle","pattern":"103","x":"0","y":"0","wait":"2","loop":"1"}},
{"name":"Foreground","status":true,"description":"マップに合わせてスクロールする近景の設定","parameters":{}},
{"name":"ItemNameMsg","status":true,"description":"メッセージウィンドウで \\ITEM[] をアイテム名に置き換えます。","parameters":{}},
{"name":"YED_WordWrap","status":true,"description":"文章の改行機能を提供します。長文を適切な位置で改行します。","parameters":{"Break Word":"true"}},
{"name":"CharacterAnimation","status":true,"description":"","parameters":{}},
{"name":"KeyItemNumber","status":true,"description":"「大事なもの」の個数表示の設定","parameters":{"KeyItem":"0","MessageWindow":"0"}},
{"name":"AKUNOU_OptionBase","status":true,"description":"オプション追加用のベーススクリプトです。\r\n入れるだけで若干オプションの操作性が向上したりもします。","parameters":{"Window Options Width":"400","Window Options Number":"13"}},
{"name":"AKUNOU_OptionMessageSpeed","status":true,"description":"オプションにメッセージ表示速度の変更を追加します。\r\n動作には同作者のオプションベーススクリプトが必須です。","parameters":{"Message Speed Term":"メッセージ速度","Message Speed List":"{\"最遅\": -2, \"遅い\": -1, \"標準\": 0, \"微妙に速い\": 1, \"速い\": 2, \"もっと速い\": 4, \"かなり速い\": 10, \"とても速い\": 20, \"瞬間\": 100}","Message Speed Default":"0"}},
{"name":"MessageSE","status":true,"description":"メッセージ中にSEを演奏する","parameters":{"SeData1":"Hotaru","SeData2":"60","SeData3":"100","SeData4":"0","SeWait":"2","StopSeSw":"1"}},
{"name":"EnemyAnimetion","status":true,"description":"","parameters":{}},
{"name":"RotationMoveGraphic","status":true,"description":"","parameters":{}}
];
